### ISSUE TITLE
add RFC 6062

### ISSUE THREAD

**Issue by sreimers** [creytiv/re#218]
I sometimes have problems with certain restrictive networks (especially universities) that block UDP connections. I think RFC 6062 with TCP/TLS Turn Peer data connections could be a good fallback here.

Before I start the implementation, do you have any special preferences I should consider?

**Comment by alfredh** [comment]
there are 2 ways to do TCP/TLS tunneling with TURN:

1. TCP from client to TURN and UDP from TURN-server to peer
2. TCP from client to TURN and TCP from TURN-server to peer (RFC 6062).

I would avoid 2.) because there is almost no SIP endpoint supporting it
so interop would fail.

I can warmly recommend 1.) instead which allows you to call even legacy
SIP endpoints. I have implemented and deployed this, with good result.

the libre TURN client already supports part of 1.) you need to create the
TCP connection in your application and do framing/de-framing of packets.
I created a TURN performance client which supports this, you can look
at the source code if you want:

https://github.com/alfredh/turnperf

have a look at `tcp_recv_handler` in allocation.c

**Comment by sreimers** [comment]
I will give 1.) a try and close this issue. Thanks for feedback.
